env:
  browser: true
  es6: true
  jest/globals: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - error
    - allow:
      - error
      - warn
      - log
  jest/no-disabled-tests:
    - warn
  jest/no-focused-tests:
    - error
  jest/no-identical-title:
    - error
  jest/valid-expect:
    - error
globals:
  __dirname: false
  console: false
  module: false
  require: false
  onmessage: false
  shallow: false
  render: false
  mount: false
