env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - error
    - allow:
      - error
      - warn
      - log
globals:
  __dirname: false
  console: false
  module: false
  require: false
  onmessage: false
  test: false
  it: false
  expect: false
